apiVersion: v1
kind: Service
metadata:
  name: github-frontend
  namespace: default
spec:
  selector:
    app: github-frontend
  ports:
    - name: http
      port: 80
      targetPort: 5000
  type: LoadBalancer
